<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-15T23:49:14 GMT" name="All Test Suite" finished-at="2022-11-15T23:49:19 GMT" duration-ms="4630">
    <groups>
    </groups>
    <test started-at="2022-11-15T23:49:14 GMT" name="Create Customer API" finished-at="2022-11-15T23:49:18 GMT" duration-ms="3685">
      <class name="com.bliss.APITestingFramework.Testcases.CreateCustomerTest">
        <test-method signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:1, instance:com.bliss.APITestingFramework.Testcases.CreateCustomerTest@e98770d]" started-at="2022-11-15T23:49:14 GMT" name="validateCreateCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:17 GMT" duration-ms="3158" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=Ayansh.aradhula@gmail.com, name=Ayansh, description=adding my son as customer from framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:1, instance:com.bliss.APITestingFramework.Testcases.CreateCustomerTest@e98770d]" started-at="2022-11-15T23:49:14 GMT" name="validateCreateCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:17 GMT" duration-ms="3135" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=myemail.id@gmail.com, name=Varma, description=adding the customer from framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:1, instance:com.bliss.APITestingFramework.Testcases.CreateCustomerTest@e98770d]" started-at="2022-11-15T23:49:14 GMT" name="validateCreateCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:17 GMT" duration-ms="3133" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=preesha.aradhula@gmail.com, name=Preesha, description=adding my daugther as customer from framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method signature="validateCreateCustomerAPI(java.util.Hashtable)[pri:1, instance:com.bliss.APITestingFramework.Testcases.CreateCustomerTest@e98770d]" started-at="2022-11-15T23:49:14 GMT" name="validateCreateCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:17 GMT" duration-ms="3135" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=baby7913@gmail.com, name=Baby, description=adding my wife as customer from framework}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPI -->
        <test-method signature="InvalidateCreateCustomerAPI(java.util.Hashtable)[pri:2, instance:com.bliss.APITestingFramework.Testcases.CreateCustomerTest@e98770d]" started-at="2022-11-15T23:49:18 GMT" name="InvalidateCreateCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:18 GMT" duration-ms="260" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=myemail.address@gmail.com, name=Krishna, description=adding the customer from framework123}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at com.bliss.APITestingFramework.Testcases.CreateCustomerTest.InvalidateCreateCustomerAPI(CreateCustomerTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidateCreateCustomerAPI -->
      </class> <!-- com.bliss.APITestingFramework.Testcases.CreateCustomerTest -->
    </test> <!-- Create Customer API -->
    <test started-at="2022-11-15T23:49:18 GMT" name="Delete Customer API" finished-at="2022-11-15T23:49:19 GMT" duration-ms="551">
      <class name="com.bliss.APITestingFramework.Testcases.DeleteCustomerTest">
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.bliss.APITestingFramework.Testcases.DeleteCustomerTest@57459491]" started-at="2022-11-15T23:49:14 GMT" name="setUP" finished-at="2022-11-15T23:49:14 GMT" duration-ms="441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="validateDeleteCustomerAPI(java.util.Hashtable)[pri:0, instance:com.bliss.APITestingFramework.Testcases.DeleteCustomerTest@57459491]" started-at="2022-11-15T23:49:18 GMT" name="validateDeleteCustomerAPI" data-provider="TestData" finished-at="2022-11-15T23:49:19 GMT" duration-ms="438" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{customerId=cus_Mnn8rYJsJY0cEN}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at com.bliss.APITestingFramework.Testcases.DeleteCustomerTest.validateDeleteCustomerAPI(DeleteCustomerTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteCustomerAPI -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.bliss.APITestingFramework.Testcases.DeleteCustomerTest@57459491]" started-at="2022-11-15T23:49:19 GMT" name="tearDown" finished-at="2022-11-15T23:49:19 GMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.bliss.APITestingFramework.Testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API -->
  </suite> <!-- All Test Suite -->
</testng-results>
